export const GOVERNORATES = [
  { ar: "القاهرة", en: "Cairo" },
  { ar: "الجيزة", en: "Giza" },
  { ar: "الإسكندرية", en: "Alexandria" },
  { ar: "الدقهلية", en: "Dakahlia" },
  { ar: "البحر الأحمر", en: "Red Sea" },
  { ar: "البحيرة", en: "Beheira" },
  { ar: "الفيوم", en: "Faiyum" },
  { ar: "الغربية", en: "Gharbia" },
  { ar: "الإسماعيلية", en: "Ismailia" },
  { ar: "المنوفية", en: "Monufia" },
  { ar: "المنيا", en: "Minya" },
  { ar: "القليوبية", en: "Qalyubia" },
  { ar: "الوادي الجديد", en: "New Valley" },
  { ar: "السويس", en: "Suez" },
  { ar: "الشرقية", en: "Sharqia" },
  { ar: "أسوان", en: "Aswan" },
  { ar: "أسيوط", en: "Asyut" },
  { ar: "بني سويف", en: "Beni Suef" },
  { ar: "بورسعيد", en: "Port Said" },
  { ar: "دمياط", en: "Damietta" },
  { ar: "جنوب سيناء", en: "South Sinai" },
  { ar: "كفر الشيخ", en: "Kafr El Sheikh" },
  { ar: "مطروح", en: "Matrouh" },
  { ar: "قنا", en: "Qena" },
  { ar: "شمال سيناء", en: "North Sinai" },
  { ar: "سوهاج", en: "Sohag" },
  { ar: "الأقصر", en: "Luxor" }
];

export const SPORTS = [
  { ar: "كرة القدم", en: "Football" },
  { ar: "كرة السلة", en: "Basketball" },
  { ar: "الكرة الطائرة", en: "Volleyball" },
  { ar: "كرة اليد", en: "Handball" },
  { ar: "التنس", en: "Tennis" },
  { ar: "السباحة", en: "Swimming" },
  { ar: "الكاراتيه", en: "Karate" },
  { ar: "الجودو", en: "Judo" },
  { ar: "المصارعة", en: "Wrestling" },
  { ar: "الملاكمة", en: "Boxing" },
  { ar: "رفع الأثقال", en: "Weightlifting" },
  { ar: "ألعاب القوى", en: "Athletics" },
  { ar: "الجمباز", en: "Gymnastics" },
  { ar: "الإسكواش", en: "Squash" },
  { ar: "تنس الطاولة", en: "Table Tennis" },
  { ar: "التجديف", en: "Rowing" },
  { ar: "الشراع", en: "Sailing" },
  { ar: "الفروسية", en: "Equestrian" },
  { ar: "الرماية", en: "Shooting" },
  { ar: "القوس والسهم", en: "Archery" },
  { ar: "الخماسي الحديث", en: "Modern Pentathlon" },
  { ar: "التايكوندو", en: "Taekwondo" },
  { ar: "الريشة الطائرة", en: "Badminton" },
  { ar: "الهوكي", en: "Hockey" },
  { ar: "الدراجات", en: "Cycling" }
];

export const EGYPTIAN_CLUBS = [
  { ar: "الأهلي", en: "Al Ahly" },
  { ar: "الزمالك", en: "Zamalek" },
  { ar: "بيراميدز", en: "Pyramids" },
  { ar: "فيوتشر", en: "Future" },
  { ar: "المصري البورسعيدي", en: "Al Masry" },
  { ar: "إنبي", en: "ENPPI" },
  { ar: "المقاولون العرب", en: "Al Mokawloon" },
  { ar: "الاتحاد السكندري", en: "Al Ittihad" },
  { ar: "فاركو", en: "Pharco" },
  { ar: "سموحة", en: "Smouha" },
  { ar: "الإسماعيلي", en: "Ismaily" },
  { ar: "البنك الأهلي", en: "National Bank" },
  { ar: "سيراميكا كليوباترا", en: "Ceramica Cleopatra" },
  { ar: "طلائع الجيش", en: "Tala'ea El Gaish" },
  { ar: "أسوان", en: "Aswan" },
  { ar: "غزل المحلة", en: "Ghazl El Mahalla" },
  { ar: "حرس الحدود", en: "Haras El Hodoud" },
  { ar: "الداخلية", en: "El Dakhleya" },
  { ar: "زد", en: "ZED" },
  { ar: "الجونة", en: "El Gouna" }
];
